services:
  postgres:
    image: postgres:17.5-alpine
    container_name: resume-builder-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: resumes
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  latex-api:
    build:
      context: ./latex-api
      dockerfile: Dockerfile
    container_name: resume-latex-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - postgres

volumes:
  pgdata:
