services:
  postgres:
    image: postgres:17.5-alpine
    container_name: resume-builder-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: resumes
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  latex-api:
    build:
      context: ./latex-api
      dockerfile: Dockerfile
    container_name: resume-latex-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: resume-frontend
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://admin:admin@postgres:5432/resumes
      - AUTH_TRUST_HOST=true
      - NEXTAUTH_URL=http://localhost:3000
      - LATEX_API_URL=http://latex-api:8000
      - FASTAPI_URL=http://host.docker.internal:8001
    ports:
      - "3000:3000"
    volumes:
      - uploads:/app/public/uploads
    depends_on:
      - postgres
      - latex-api
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  pgdata:
  uploads:
